image: circleci/ruby:2-node

before_script:
  - sudo apt-get install -y awscli
  - bundle install
  - npm install

stages:
  - deploy

push_to_s3:
  stage: deploy
  script:
    - npm run build
    - aws s3 sync dist s3://tech-action-working-group/ --delete --exclude "node_modules/*" --exclude "sass/*" --exclude ".git/*"
  only:
    - master
