image: circleci/ruby:2-node

before_script:
  - apt-get install -y awscli
  - bundle install
  - npm install

stages:
  - build
  - deploy

build_site:
  stage: build
  script:
    - npm run build
  only:
    - master
