title: Tech Action Working Group
description: New York City Tech Action Working Group

source: src
destination: dist
sass:
  sass_dir: assets/_sass
exclude: ['*.js']
permalink: /posts/:slug/
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
facebook: NYCDSATechWG
twitter: NYCDSATechWG
email: techaction.nycdsa@gmail.com
