title: Tech Action Working Group
description: New York City Tech Action Working Group
url: https://www.techaction.nyc

source: src
destination: dist
sass:
  sass_dir: assets/_sass
exclude: []
permalink: /posts/:slug/
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
twitter: NYCDSATechWG
instagram: nycdsatechaction
bluesky: nycdsatech.bsky.social
email: tech.action@socialists.nyc
calendar_id: 008c087f2e755e8de1e297b1955d22b1df9c8fb6c322bbe657e526777084afb1@group.calendar.google.com
